[project]
name = "wordhop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "elevenlabs>=1.57.0",
    "llama-api-client>=0.1.0",
    "python-dotenv>=1.1.0",
]
